CREATE TABLE IF NOT EXISTS users (
id UUID PRIMARY KEY,
firstname TEXT NOT NULL,
lastname TEXT NOT NULL,
email TEXT NOT NULL UNIQUE,
age INTEGER NOT NULL CHECK (age >= 0),
created TIMESTAMP NOT NULL
);
