env: "local"
data:
  postgres:
    host: "localhost"
    port: 57819
    user: "test"
    password: "test"
    dbname: "integtest_users_tests_db"
http_server:
  address: localhost:8080
  timeout: 4s
  idle_timeout: 60s